"""Deterministic JSON, schema, Markdown, Mermaid, and static-HTML projections."""

from __future__ import annotations

import hashlib
import html
import json
import re
from collections import Counter, defaultdict

from sre_kb.atlas.model import AtlasNode, AtlasSnapshot, RuntimeEvidence


def canonical_json(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def render_files(
    snapshot: AtlasSnapshot,
    *,
    max_diagram_nodes: int = 80,
    include_html: bool = True,
) -> dict[str, str]:
    data = snapshot.model_dump(mode="json", exclude_none=True)
    source_mermaid = source_graph(snapshot, max_nodes=max_diagram_nodes)
    call_mermaid = call_graph(snapshot, max_nodes=max_diagram_nodes)
    runtime_mermaid = runtime_graph(snapshot, max_nodes=max_diagram_nodes)
    files = {
        "atlas.json": canonical_json(data),
        "CodebaseAtlas.schema.json": canonical_json(AtlasSnapshot.model_json_schema()),
        "RuntimeEvidence.schema.json": canonical_json(RuntimeEvidence.model_json_schema()),
        "README.md": generated_readme(snapshot),
        "DEPENDENCY-SNAPSHOT.md": dependency_snapshot(snapshot),
        "OPERATIONAL-SIGNALS.md": operational_signals(snapshot),
        "source-graph.mmd": source_mermaid,
        "source-graph.md": _mermaid_page(
            "Resolver-backed source dependency view",
            source_mermaid,
            "Scope: resolved production import edges, collapsed by package/namespace group.",
        ),
        "call-graph.mmd": call_mermaid,
        "call-graph.md": _mermaid_page(
            "Resolver-backed cross-file call view",
            call_mermaid,
            "Scope: conservative statically resolved production call edges; not runtime traces.",
        ),
        "runtime-graph.mmd": runtime_mermaid,
        "runtime-graph.md": _mermaid_page(
            "Imported runtime dependency view",
            runtime_mermaid,
            "Scope: only edges present in configured runtime-evidence files.",
        ),
        "licenses.json": canonical_json(
            {
                "project": {
                    "status": snapshot.metadata.projectLicense,
                    "source": snapshot.metadata.projectLicenseSource,
                },
                "dependencies": [
                    item.model_dump(mode="json", exclude_none=True) for item in snapshot.licenses
                ],
            }
        ),
    }
    if include_html:
        files["atlas.html"] = html_explorer(snapshot)
    manifest = {
        name: "sha256:" + hashlib.sha256(content.encode("utf-8")).hexdigest()
        for name, content in sorted(files.items())
    }
    files["manifest.json"] = canonical_json(
        {
            "apiVersion": "sre.kb/atlas-render/v1alpha1",
            "files": manifest,
        }
    )
    return files


def generated_readme(snapshot: AtlasSnapshot) -> str:
    source_edges = sum(edge.scope == "source" for edge in snapshot.edges)
    return f"""# Generated codebase atlas evidence

This directory is generated by `sre-kb atlas`. Do not hand-edit it; update `.sre/atlas.yaml`,
source, or imported evidence and regenerate.

- Machine contract: [`atlas.json`](atlas.json)
- Schema: [`CodebaseAtlas.schema.json`](CodebaseAtlas.schema.json)
- Source graph: [`source-graph.md`](source-graph.md)
- Cross-file call graph: [`call-graph.md`](call-graph.md)
- Runtime graph: [`runtime-graph.md`](runtime-graph.md)
- Dependency metrics, import matrix, and cycle-closing citations: [`DEPENDENCY-SNAPSHOT.md`](DEPENDENCY-SNAPSHOT.md)
- Static operational signals: [`OPERATIONAL-SIGNALS.md`](OPERATIONAL-SIGNALS.md)
- License inventory: [`licenses.json`](licenses.json)
- Searchable explorer: [`atlas.html`](atlas.html)

Snapshot: {len(snapshot.nodes)} nodes, {len(snapshot.edges)} edges, {source_edges} resolved production
source edges, {len(snapshot.metrics.cycles)} source cycle(s), and {len(snapshot.unknowns)} explicit
unknown(s). The snapshot also contains {len(snapshot.signals)} static operational signal(s); these
are discovery hints, not runtime observations.
"""


def dependency_snapshot(snapshot: AtlasSnapshot) -> str:
    names = {node.id: node for node in snapshot.nodes}
    rows = []
    for metric in sorted(
        snapshot.metrics.coupling,
        key=lambda item: (-item.afferent, -item.efferent, item.node),
    ):
        node = names.get(metric.node)
        label = node.path if node and node.path else (node.name if node else metric.node)
        instability = "n/a" if metric.instability is None else f"{metric.instability:.3f}"
        rows.append(
            f"| `{_markdown(label)}` | {metric.granularity} | {metric.afferent} | "
            f"{metric.efferent} | {instability} |"
        )
    cycle_blocks = []
    for index, cycle in enumerate(snapshot.metrics.cycles, start=1):
        members = [
            names[member].path or names[member].name if member in names else member
            for member in cycle.members
        ]
        cycle_blocks.append(
            f"{index}. **{cycle.granularity}** — "
            + " → ".join(f"`{_markdown(value)}`" for value in members)
        )
    unknown_counts = Counter(unknown.code for unknown in snapshot.unknowns)
    unknown_rows = [
        f"| `{_markdown(code)}` | {count} |" for code, count in sorted(unknown_counts.items())
    ]
    return f"""# Dependency snapshot

Evidence scope: resolver-backed production source edges only for coupling and cycle metrics.
`Ca` is distinct incoming neighbors, `Ce` is distinct outgoing neighbors, and
`I = Ce / (Ca + Ce)`. No health or severity grade is inferred.

## Coupling

| Node | Granularity | Ca | Ce | I |
|---|---|---:|---:|---:|
{chr(10).join(rows) if rows else "| _No coupled source nodes_ | module | 0 | 0 | n/a |"}

## Strongly connected components

{chr(10).join(cycle_blocks) if cycle_blocks else "No non-trivial source SCC was resolved."}

{_package_import_views(snapshot)}
## Resolver blind spots

| Unknown code | Count |
|---|---:|
{chr(10).join(unknown_rows) if unknown_rows else "| _None recorded_ | 0 |"}
"""


_MAX_MATRIX_GROUPS = 14
_MAX_HOTSPOTS = 15
_MAX_CYCLE_CITATIONS = 12


def _group_metric_id(node: AtlasNode) -> str:
    return f"group:{node.project or '?'}:{node.group or node.name}"


def _group_display(group_id: str) -> str:
    return group_id.split(":", 2)[-1]


def _evidence_location(item) -> str:
    if item.path and item.lines:
        if item.lines.start == item.lines.end:
            return f"{item.path}:{item.lines.start}"
        return f"{item.path}:{item.lines.start}-{item.lines.end}"
    return item.path or ""


def _package_import_views(snapshot: AtlasSnapshot) -> str:
    nodes = {node.id: node for node in snapshot.nodes}
    weights: Counter[tuple[str, str]] = Counter()
    citations: dict[tuple[str, str], list[str]] = defaultdict(list)
    for edge in snapshot.edges:
        if edge.scope != "source" or edge.kind != "imports" or edge.unresolved:
            continue
        source = nodes.get(edge.source)
        target = nodes.get(edge.target)
        if source is None or target is None:
            continue
        src = _group_metric_id(source)
        dst = _group_metric_id(target)
        if src == dst:
            continue
        weights[(src, dst)] += max(len(edge.evidence), 1)
        for item in edge.evidence:
            location = _evidence_location(item)
            if location and location not in citations[(src, dst)]:
                citations[(src, dst)].append(location)

    if not weights:
        return """## Cross-package import matrix

No cross-package production import edges were resolved.

## Highest-traffic cross-package imports

No cross-package production import edges were resolved.

"""

    outgoing: dict[str, list[tuple[str, int]]] = defaultdict(list)
    incoming: dict[str, list[tuple[str, int]]] = defaultdict(list)
    degree: Counter[str] = Counter()
    for (src, dst), count in weights.items():
        outgoing[src].append((dst, count))
        incoming[dst].append((src, count))
        degree[src] += count
        degree[dst] += count

    cycle_members = {
        member
        for cycle in snapshot.metrics.cycles
        if cycle.granularity == "group"
        for member in cycle.members
    }
    ranked = sorted(degree, key=lambda gid: (gid not in cycle_members, -degree[gid], gid))
    matrix_groups = ranked[:_MAX_MATRIX_GROUPS]
    omitted = len(ranked) - len(matrix_groups)
    omitted_note = (
        f" The matrix shows {len(matrix_groups)} of {len(ranked)} packages "
        f"(SCC members first, then highest import traffic); {omitted} lower-traffic "
        "package(s) remain in the incoming/outgoing list."
        if omitted
        else ""
    )

    header = "| | " + " | ".join(f"`{_markdown(_group_display(gid))}`" for gid in matrix_groups) + " |"
    divider = "|" + "---|" * (len(matrix_groups) + 1)
    matrix_rows = []
    for src in matrix_groups:
        cells = []
        for dst in matrix_groups:
            if src == dst:
                cells.append("-")
            else:
                count = weights.get((src, dst), 0)
                cells.append(str(count) if count else "0")
        matrix_rows.append(
            f"| `{_markdown(_group_display(src))}` | " + " | ".join(cells) + " |"
        )

    hotspot_rows = [
        f"| `{_markdown(_group_display(src))}` | `{_markdown(_group_display(dst))}` | {count} |"
        for (src, dst), count in weights.most_common(_MAX_HOTSPOTS)
    ]

    direction_blocks = []
    for gid in sorted(set(outgoing) | set(incoming), key=_group_display):
        out = ", ".join(
            f"`{_markdown(_group_display(dst))}` ({count})"
            for dst, count in sorted(outgoing.get(gid, []), key=lambda item: (-item[1], item[0]))
        ) or "_none_"
        inn = ", ".join(
            f"`{_markdown(_group_display(src))}` ({count})"
            for src, count in sorted(incoming.get(gid, []), key=lambda item: (-item[1], item[0]))
        ) or "_none_"
        direction_blocks.append(
            f"- `{_markdown(_group_display(gid))}` — outgoing: {out}; incoming: {inn}"
        )

    cycle_blocks = []
    for index, cycle in enumerate(
        (item for item in snapshot.metrics.cycles if item.granularity == "group"),
        start=1,
    ):
        members = set(cycle.members)
        lines = []
        for (src, dst), locations in sorted(citations.items()):
            if src not in members or dst not in members:
                continue
            shown = locations[:_MAX_CYCLE_CITATIONS]
            extra = len(locations) - len(shown)
            loc_text = ", ".join(f"`{_markdown(location)}`" for location in shown)
            if extra:
                loc_text += f" (+{extra} more)"
            lines.append(
                f"  - `{_markdown(_group_display(src))}` → "
                f"`{_markdown(_group_display(dst))}`: {loc_text}"
            )
        body = "\n".join(lines) if lines else "  - _No cited cross-package imports inside this SCC._"
        cycle_blocks.append(
            f"{index}. "
            + " → ".join(f"`{_markdown(_group_display(member))}`" for member in cycle.members)
            + f"\n{body}"
        )

    return f"""## Cross-package import matrix

Row depends on column. Cell values are resolver-backed production import counts, not API calls
and not a health grade.{omitted_note}

{header}
{divider}
{chr(10).join(matrix_rows)}

## Highest-traffic cross-package imports

| From | To | Import count |
|---|---|---:|
{chr(10).join(hotspot_rows)}

Counts are edge weights. They do not assign severity or a refactoring mandate.

## Incoming and outgoing by package

{chr(10).join(direction_blocks)}

## Cycle-closing imports

{chr(10).join(cycle_blocks) if cycle_blocks else "No group-level SCC was resolved."}

"""


def operational_signals(snapshot: AtlasSnapshot) -> str:
    rows = []
    for signal in snapshot.signals:
        lines = signal.evidence.lines
        location = (
            f"{signal.path}:{lines.start}"
            if lines and lines.start == lines.end
            else f"{signal.path}:{lines.start}-{lines.end}" if lines else signal.path
        )
        excerpt = " ".join(signal.text.split())
        if len(excerpt) > 140:
            excerpt = excerpt[:137] + "..."
        rows.append(
            f"| `{_markdown(signal.category)}` | `{_markdown(location)}` | "
            f"{_markdown(signal.summary)} | `{_markdown(excerpt)}` |"
        )
    return f"""# Static operational signals

Evidence scope: `STATIC_EXTRACTED` syntax and configuration evidence only. These records help an
SRE find likely process controls, network and datastore calls, deployment settings, migrations,
and health checks. They are not runtime evidence, do not prove production topology, and are not
automatically safe runbook commands.

| Category | Location | Why it was selected | Static excerpt |
|---|---|---|---|
{chr(10).join(rows) if rows else "| _None_ | - | No operational signal matched | - |"}
"""


def source_graph(snapshot: AtlasSnapshot, *, max_nodes: int) -> str:
    nodes = {node.id: node for node in snapshot.nodes}
    selected = [
        edge
        for edge in snapshot.edges
        if edge.scope == "source"
        and edge.kind == "imports"
        and not edge.unresolved
        and edge.source in nodes
        and edge.target in nodes
    ]
    group_labels: dict[str, str] = {}
    grouped_edges: Counter[tuple[str, str]] = Counter()
    for edge in selected:
        source_group = _group_key(nodes[edge.source])
        target_group = _group_key(nodes[edge.target])
        if source_group == target_group:
            continue
        group_labels[source_group] = _group_label(nodes[edge.source])
        group_labels[target_group] = _group_label(nodes[edge.target])
        grouped_edges[(source_group, target_group)] += 1
    ranked = [
        key
        for key, _ in Counter(
            endpoint for edge in grouped_edges for endpoint in edge
        ).most_common(max_nodes)
    ]
    allowed = set(ranked)
    lines = ["flowchart LR"]
    if not group_labels:
        lines.append('  empty["No resolved production source edges"]')
        return "\n".join(lines) + "\n"
    for key in sorted(allowed):
        lines.append(f'  {_mermaid_id(key)}["{_mermaid_label(group_labels[key])}"]')
    for (source, target), count in sorted(grouped_edges.items()):
        if source in allowed and target in allowed:
            lines.append(f"  {_mermaid_id(source)} -->|{count}| {_mermaid_id(target)}")
    omitted = len(group_labels) - len(allowed)
    if omitted > 0:
        lines.append(f'  omitted["{omitted} lower-connectivity group(s) omitted"]')
    return "\n".join(lines) + "\n"


def call_graph(snapshot: AtlasSnapshot, *, max_nodes: int) -> str:
    nodes = {node.id: node for node in snapshot.nodes}
    selected = [
        edge
        for edge in snapshot.edges
        if edge.scope == "source"
        and edge.kind == "calls"
        and not edge.unresolved
        and edge.source in nodes
        and edge.target in nodes
    ]
    group_labels: dict[str, str] = {}
    grouped_edges: Counter[tuple[str, str]] = Counter()
    for edge in selected:
        source_group = _group_key(nodes[edge.source])
        target_group = _group_key(nodes[edge.target])
        if source_group == target_group:
            continue
        group_labels[source_group] = _group_label(nodes[edge.source])
        group_labels[target_group] = _group_label(nodes[edge.target])
        grouped_edges[(source_group, target_group)] += 1
    ranked = [
        key
        for key, _ in Counter(
            endpoint for edge in grouped_edges for endpoint in edge
        ).most_common(max_nodes)
    ]
    allowed = set(ranked)
    lines = ["flowchart LR"]
    if not group_labels:
        lines.append('  empty["No statically resolved production call edges"]')
        return "\n".join(lines) + "\n"
    for key in sorted(allowed):
        lines.append(f'  {_mermaid_id(key)}["{_mermaid_label(group_labels[key])}"]')
    for (source, target), count in sorted(grouped_edges.items()):
        if source in allowed and target in allowed:
            lines.append(f"  {_mermaid_id(source)} -->|{count} call(s)| {_mermaid_id(target)}")
    omitted = len(group_labels) - len(allowed)
    if omitted > 0:
        lines.append(f'  omitted["{omitted} lower-connectivity group(s) omitted"]')
    return "\n".join(lines) + "\n"


def runtime_graph(snapshot: AtlasSnapshot, *, max_nodes: int) -> str:
    nodes = {node.id: node for node in snapshot.nodes}
    edges = [edge for edge in snapshot.edges if edge.scope == "runtime"]
    ranked = [
        key
        for key, _ in Counter(endpoint for edge in edges for endpoint in (edge.source, edge.target)).most_common(
            max_nodes
        )
    ]
    allowed = set(ranked)
    lines = ["flowchart LR"]
    if not edges:
        lines.append('  empty["No runtime evidence imported"]')
        return "\n".join(lines) + "\n"
    for node_id in sorted(allowed):
        node = nodes.get(node_id)
        label = node.name if node else node_id
        lines.append(f'  {_mermaid_id(node_id)}["{_mermaid_label(label)}"]')
    for edge in sorted(edges, key=lambda item: (item.source, item.target, item.kind)):
        if edge.source in allowed and edge.target in allowed:
            lines.append(
                f"  {_mermaid_id(edge.source)} -->|{_mermaid_label(edge.kind)}| "
                f"{_mermaid_id(edge.target)}"
            )
    return "\n".join(lines) + "\n"


def _group_key(node: AtlasNode) -> str:
    return f"{node.project or '?'}::{node.group or node.name}"


def _group_label(node: AtlasNode) -> str:
    return f"{node.project or '?'} / {node.group or node.name}"


def _mermaid_id(value: str) -> str:
    return "n_" + hashlib.sha256(value.encode("utf-8")).hexdigest()[:12]


def _mermaid_label(value: str) -> str:
    clean = re.sub(r"[\r\n\t\"`[\]{}<>|]", " ", value)
    clean = re.sub(r"\s+", " ", clean).strip()
    return clean[:100]


def _markdown(value: str) -> str:
    return value.replace("|", "\\|").replace("`", "'").replace("\n", " ")


def _mermaid_page(title: str, mermaid: str, scope: str) -> str:
    return f"""# {title}

{scope}

```mermaid
{mermaid.rstrip()}
```
"""


def html_explorer(snapshot: AtlasSnapshot) -> str:
    payload = json.dumps(
        snapshot.model_dump(mode="json", exclude_none=True),
        sort_keys=True,
        ensure_ascii=False,
    )
    payload = (
        payload.replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )
    title = html.escape(snapshot.metadata.repository)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Security-Policy"
    content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{title} codebase atlas</title>
  <style>
    :root {{ color-scheme: light dark; --ink:#172033; --muted:#5d687b; --paper:#f6f1e7;
      --panel:#fffdf8; --accent:#d4552d; --line:#d8cfbf; }}
    @media (prefers-color-scheme:dark) {{ :root {{ --ink:#f5efe5; --muted:#b9b0a3;
      --paper:#15181e; --panel:#20242c; --accent:#ff8159; --line:#3b414c; }} }}
    * {{ box-sizing:border-box; }} body {{ margin:0; font:15px/1.5 ui-sans-serif,system-ui;
      color:var(--ink); background:var(--paper); }}
    header {{ padding:2rem clamp(1rem,4vw,4rem) 1.2rem; border-bottom:1px solid var(--line); }}
    h1 {{ margin:0 0 .35rem; font:700 clamp(1.7rem,4vw,3rem)/1.05 ui-serif,Georgia; }}
    .meta {{ color:var(--muted); }} main {{ padding:1rem clamp(1rem,4vw,4rem) 3rem; }}
    .controls {{ display:grid; grid-template-columns:minmax(16rem,1fr) repeat(2,minmax(9rem,auto));
      gap:.7rem; position:sticky; top:0; padding:.8rem 0; background:var(--paper); }}
    input,select {{ width:100%; padding:.7rem .8rem; border:1px solid var(--line);
      border-radius:.4rem; background:var(--panel); color:var(--ink); }}
    .summary {{ display:flex; gap:1rem; color:var(--muted); margin:.5rem 0 1rem; }}
    table {{ width:100%; border-collapse:collapse; background:var(--panel); }}
    th,td {{ padding:.58rem .65rem; border-bottom:1px solid var(--line); text-align:left;
      vertical-align:top; }} th {{ color:var(--muted); font-size:.78rem; text-transform:uppercase;
      letter-spacing:.06em; }} code {{ color:var(--accent); overflow-wrap:anywhere; }}
    .pill {{ display:inline-block; padding:.08rem .38rem; border:1px solid var(--line);
      border-radius:1rem; font-size:.78rem; }} .hidden {{ display:none; }}
    @media(max-width:760px) {{ .controls {{ grid-template-columns:1fr; position:static; }}
      th:nth-child(4),td:nth-child(4) {{ display:none; }} }}
  </style>
</head>
<body>
<header><h1>{title}</h1><div class="meta">Evidence-backed codebase atlas · offline projection</div></header>
<main>
  <div class="controls">
    <label><span class="hidden">Search</span><input id="q" type="search"
      placeholder="Search paths, packages, owners, evidence…"></label>
    <label><span class="hidden">Record kind</span><select id="record">
      <option value="nodes">Nodes</option><option value="edges">Edges</option>
      <option value="unknowns">Unknowns</option></select></label>
    <label><span class="hidden">Scope</span><select id="scope"><option value="">All scopes</option></select></label>
  </div>
  <div class="summary" id="summary"></div>
  <div style="overflow:auto"><table><thead><tr id="head"></tr></thead><tbody id="rows"></tbody></table></div>
</main>
<script id="atlas-data" type="application/json">{payload}</script>
<script>
const atlas=JSON.parse(document.getElementById("atlas-data").textContent);
const q=document.getElementById("q"), record=document.getElementById("record"),
  scope=document.getElementById("scope"), rows=document.getElementById("rows"),
  head=document.getElementById("head"), summary=document.getElementById("summary");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({{"&":"&amp;","<":"&lt;",">":"&gt;",
  '"':"&quot;","'":"&#39;"}}[c]));
const scopes=[...new Set(atlas.edges.map(e=>e.scope))].sort();
for(const value of scopes) scope.insertAdjacentHTML("beforeend",
  `<option value="${{esc(value)}}">${{esc(value)}}</option>`);
function render(){{
  const kind=record.value, needle=q.value.toLowerCase();
  let data=atlas[kind]||[];
  if(kind==="edges"&&scope.value) data=data.filter(x=>x.scope===scope.value);
  if(needle) data=data.filter(x=>JSON.stringify(x).toLowerCase().includes(needle));
  const columns=kind==="nodes"?["type","name","path","group","owners"]:
    kind==="edges"?["kind","source","target","scope","resolver"]:["code","message","path","neededEvidence"];
  head.innerHTML=columns.map(x=>`<th>${{esc(x)}}</th>`).join("");
  rows.innerHTML=data.map(item=>"<tr>"+columns.map(column=>{{
    let value=item[column]; if(Array.isArray(value)) value=value.join(", ");
    return `<td>${{column==="type"||column==="scope"?`<span class="pill">${{esc(value)}}</span>`:
      `<code>${{esc(value)}}</code>`}}</td>`;
  }}).join("")+"</tr>").join("");
  summary.textContent=`${{data.length}} shown · ${{atlas.nodes.length}} nodes · `+
    `${{atlas.edges.length}} edges · ${{atlas.unknowns.length}} unknowns`;
}}
[q,record,scope].forEach(element=>element.addEventListener("input",render)); render();
</script>
</body>
</html>
"""
