"""Generate docs/SCHEMA-REFERENCE.md from the kind registry + per-kind JSON Schemas.

The schemas are the single source of truth for artifact shapes; this renders them into the
one human-readable field reference skills and reviewers can link, so prose field guides
don't drift from the validator. CI keeps the file current (tests/test_schema_governance.py
regenerates and compares); regenerate with `make schema-ref` after any schema change.
"""

from __future__ import annotations

import json
from pathlib import Path

from sre_kb.config import schemas_dir
from sre_kb.registry import kinds, schema_for

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "SCHEMA-REFERENCE.md"

_HEADER = """\
# Schema reference — every kind's `spec`, generated

<!-- GENERATED by tools/gen_schema_ref.py from src/sre_kb/schemas/ — do not edit by hand.
     Regenerate with `make schema-ref`; CI fails if this file is stale. -->

One row per field of each registered kind's `spec`, rendered from the same JSON Schemas the
validator enforces (`additionalProperties: false` — fields not listed here are rejected).
A nested field marked required is required *within its parent object* when that parent is
present. Skills and reviews should link here rather than restating shapes in prose.
"""


def _cell(text: object) -> str:
    """Collapse whitespace and escape `|` so arbitrary schema text can't split a table row."""
    return " ".join(str(text).split()).replace("|", "\\|")


def _is_array(prop: dict) -> bool:
    t = prop.get("type")
    return t == "array" or (isinstance(t, list) and "array" in t)


def _type_of(prop: dict) -> str:
    if any(k in prop for k in ("anyOf", "oneOf", "allOf", "$ref")):
        return "composite (see schema)"  # composed shapes aren't flattened into rows
    t = prop.get("type")
    if isinstance(t, list):
        return " or ".join(str(x) for x in t)  # not "|" — it would split the markdown cell
    if t == "array":
        items = prop.get("items") or {}
        inner = items.get("type")
        return f"array of {inner}" if isinstance(inner, str) and inner != "object" else "array"
    return str(t) if t else ("const" if "const" in prop else "any")


def _notes(prop: dict) -> str:
    notes = []
    if "enum" in prop:
        notes.append("one of: " + ", ".join(f"`{_cell(v)}`" for v in prop["enum"]))
    desc = prop.get("description")
    if desc:
        notes.append(_cell(desc))
    return " — ".join(notes)


def _rows(props: dict, required: set[str], prefix: str = "") -> list[tuple[str, str, bool, str]]:
    rows: list[tuple[str, str, bool, str]] = []
    for name, prop in props.items():
        if not isinstance(prop, dict):
            continue
        path = f"{prefix}{name}"
        rows.append((path, _type_of(prop), name in required, _notes(prop)))
        child = prop.get("items") if _is_array(prop) else prop
        if isinstance(child, dict) and isinstance(child.get("properties"), dict):
            suffix = "[]." if _is_array(prop) else "."
            rows.extend(_rows(child["properties"], set(child.get("required") or []),
                              f"{path}{suffix}"))
    return rows


def generate() -> str:
    out = [_HEADER]
    for kind in kinds():
        schema_rel = schema_for(kind)
        if not schema_rel:
            continue
        schema = json.loads((schemas_dir().parent / schema_rel).read_text(encoding="utf-8"))
        spec = (schema.get("properties") or {}).get("spec") or {}
        out.append(f"## {kind}")
        desc = schema.get("description")
        if desc:
            out.append("")
            out.append(_cell(desc))
        out.append("")
        out.append("| field | type | required | notes |")
        out.append("|---|---|---|---|")
        required = set(spec.get("required") or [])
        for path, ftype, req, notes in _rows(spec.get("properties") or {}, required):
            out.append(f"| `{path}` | {ftype} | {'yes' if req else ''} | {notes} |")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main() -> None:
    OUTPUT.write_text(generate(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
